[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.6",
    "scipy>=1.16.1",
    "soundfile>=0.13.1",
    "streamlit>=1.49.1",
]
